// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Location = sequelize.define('location', {
    isActive: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    createdAt: {
      type: DataTypes.DATE,
      defaultValue: "CURRENT_TIMESTAMP",
    },
    updatedAt: {
      type: DataTypes.DATE,
      defaultValue: "CURRENT_TIMESTAMP",
    },
    username: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'location',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Location.associate = (models) => {
    Location.belongsTo(models.area, {
      foreignKey: {
        name: 'areaIdKey',
        field: 'area_id',
      },
      as: 'area',
    });
    Location.belongsTo(models.city, {
      foreignKey: {
        name: 'cityIdKey',
        field: 'city_id',
      },
      as: 'city',
    });
    Location.belongsTo(models.country, {
      foreignKey: {
        name: 'countryCodeKey',
        field: 'country_code',
      },
      targetKey: 'countryCode',
      as: 'countryCode',
    });
    Location.belongsTo(models.region, {
      foreignKey: {
        name: 'regionIdKey',
        field: 'region_id',
      },
      as: 'region',
    });
    Location.hasMany(models.property, {
      foreignKey: {
        name: 'locationIdKey',
        field: 'location_id',
      },
      as: 'properties',
    });
  };

  return Location;
};
