// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Revinfo = sequelize.define('revinfo', {
    rev: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },
    revtstmp: {
      type: DataTypes.BIGINT,
    },
  }, {
    tableName: 'revinfo',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Revinfo.associate = (models) => {
    Revinfo.hasMany(models.bookingTransactionAud, {
      foreignKey: {
        name: 'revKey',
        field: 'rev',
      },
      sourceKey: 'rev',
      as: 'revBookingTransactionAuds',
    });
    Revinfo.hasMany(models.propertyPriceAud, {
      foreignKey: {
        name: 'revKey',
        field: 'rev',
      },
      sourceKey: 'rev',
      as: 'revPropertyPriceAuds',
    });
  };

  return Revinfo;
};
